env:
  - distro: ubuntuxenial
    init: "/sbin/init"

services:
  - docker

script:
  - container_id=$(mktemp)
  - docker build -t container_under_test .
  - docker run --detach container_under_test "${init}" > "${container_id}"
  - docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible --version
  - docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible all -m ping

notifications:
  slack:
    secure: Ka78Zw5/GLMixS4AB35nvSQZSN8LNn4DthzrVglXp7QKPgWT7gz2OnXp65mgwmclMcYBipR8JAjE5/QW2v8u5nGaJk2dMB20E6sl6uyZXkU31bsbLH6kopWE/VxGPHk9YwMlsX5xBRMS0XHWKBYoMt2R4qCA0sh7FIT0AC/Ee2SkbSUGsz7R4ag+6VbmFBrS4nQw7TGpZd9ZLncUMQFWss95yqVwb8T4w8kwdBHyy0kzvdD6ThnNiipSomhaLdmNDSyrTXSISr8q3A83PaWFpebcP58dvbzlEdaNMkNgibZOPtD/yJDOcrF0APyxygu0WSy5N57ybhyTIHKXjJrNGnE0Mb6o7e8GNnqcGZiiz9+7hzOPnhShYSQWvcsyatVqDUa4RsxJHCPa5vfG2NtZBPTbB4StdL5MkLPO+7qhCk04t+t9HC1aClpNd0nY9J6eR1yDOCAA/Y3ECyBoxCitkpl0kvXjonfbv3MYSuLp5Zmd0guuuCGI+GHmc+rX3d2SnrNdzlqr1vaUyyiM9s5RgXRVJDrmPUATusLaNwodyYFQPN1C5CM+eVfZLmfurZTz0sH0dGARx0Qrj34AKBpqgcKcPlz1gB0frYEGM/AdbaG8VNVdelhoRwgoErLkECd1aUJgkX+Gafid+2Y3n/x9+vyDv72jybWIT5aXFqIQ64E=
